#!/bin/bash
PEPTIDE_DATASET=$1
SCORE_MATRIX=$2
POCKET_WEIGHTS=$3
THRESHOLD=$4

python3 bin/predict.py ${PEPTIDE_DATASET} ${SCORE_MATRIX} ${POCKET_WEIGHTS} ${THRESHOLD} > ${PEPTIDE_DATASET}.predict.log
